# Generated by Django 5.2.5 on 2025-09-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
    ]
