# Generated by Django 5.2.5 on 2025-09-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_task_update_date_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='update_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
